import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { streamGoogleVertex, streamSimpleGoogleVertex } from "../../ref/pi/packages/ai/src/providers/google-vertex.ts";
const spec=JSON.parse(readFileSync(process.argv[2]!,"utf8"));
const drop=new Set(["host","content-length","connection","accept-encoding","accept-language","sec-fetch-mode","user-agent"]);
async function run(c:any){const requests:any[]=[];let i=0;const server=createServer((req,res)=>{const bs:Buffer[]=[];req.on("data",x=>bs.push(x));req.on("end",()=>{const text=Buffer.concat(bs).toString();requests.push({method:req.method,path:req.url,headers:Object.fromEntries(Object.entries(req.headers).filter(([k])=>!drop.has(k)).map(([k,v])=>[k,Array.isArray(v)?v.join(", "):v??""]).sort(([a],[b])=>a.localeCompare(b))),body:text?(req.headers["content-type"]?.startsWith("application/json")?JSON.parse(text):text):null});if(req.url==="/token"){res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({access_token:"adc-token",token_type:"Bearer",expires_in:3600}));return}const r=c.responses[i++]??c.responses.at(-1);if(!r){res.destroy();return}const body=r.chunks?r.chunks.map((x:any)=>`data: ${JSON.stringify(x)}\n\n`).join(""):r.json!==undefined?JSON.stringify(r.json):r.text??"";res.writeHead(r.status,{"content-type":r.chunks?"text/event-stream":r.json!==undefined?"application/json":"text/plain"});res.end(body)})});await new Promise<void>(ok=>server.listen(0,"127.0.0.1",ok));const url=`http://127.0.0.1:${(server.address() as any).port}`;const model={...spec.models[c.model],...(!c.noServerBase?{baseUrl:url+(c.baseSuffix??"")}:{})};let dir:string|undefined;const old=process.env.GOOGLE_APPLICATION_CREDENTIALS;if(c.adc){dir=mkdtempSync(join(tmpdir(),"pi-vertex-oracle-"));const path=join(dir,"adc.json");writeFileSync(path,JSON.stringify({type:"external_account_authorized_user",client_id:"client",client_secret:"secret",refresh_token:"refresh",token_url:`${url}/token`}));process.env.GOOGLE_APPLICATION_CREDENTIALS=path}const events:any[]=[];let result:any,syncError:string|undefined;try{const s=c.simple?streamSimpleGoogleVertex(model,c.context,c.options):streamGoogleVertex(model,c.context,c.options);for await(const e of s){const{partial,message,error,...rest}=e as any;events.push(rest)}result={...await s.result(),timestamp:0}}catch(e){syncError=e instanceof Error?e.message:String(e)}finally{server.close();if(old===undefined)delete process.env.GOOGLE_APPLICATION_CREDENTIALS;else process.env.GOOGLE_APPLICATION_CREDENTIALS=old;if(dir)rmSync(dir,{recursive:true,force:true})}return{name:c.name,requests,...(syncError?{syncError}:{events,result})}}
async function main(){const cases=[];for(const c of spec.cases)cases.push(await run(c));console.log(JSON.stringify({cases},null,"\t"));}
main().catch(error=>{console.error(error);process.exitCode=1});
