//! A.3 source-language gate: reject new first-party foreign-language files.

use std::collections::BTreeSet;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Language {
    TypeScript,
    Python,
    Shell,
    JavaScript,
}

impl Language {
    pub fn label(&self) -> &'static str {
        match self {
            Language::TypeScript => "TypeScript",
            Language::Python => "Python",
            Language::Shell => "shell",
            Language::JavaScript => "JavaScript",
        }
    }
}

/// Detect the foreign language of a file by extension, or by shebang for
/// extension-less executables. Returns `None` for files that are not
/// foreign-language source (Rust, Lua, JSON, markdown, etc.).
pub fn detect(path: &Path, first_line: Option<&str>) -> Option<Language> {
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_ascii_lowercase())
        .unwrap_or_default();
    match ext.as_str() {
        "ts" | "tsx" | "mts" | "cts" => return Some(Language::TypeScript),
        "py" | "pyw" => return Some(Language::Python),
        "sh" | "bash" => return Some(Language::Shell),
        "js" | "mjs" | "cjs" => return Some(Language::JavaScript),
        _ => {}
    }
    // Extension-less executable: sniff the shebang.
    if let Some(line) = first_line {
        let line = line.trim_start();
        if let Some(rest) = line.strip_prefix("#!") {
            let rest = rest.trim();
            // Resolve `env python3`, `/usr/bin/python3`, `python`, `bash`, `sh`.
            let lower = rest.to_ascii_lowercase();
            let mut tokens = lower.split_whitespace();
            let first = tokens.next().unwrap_or("");
            // `env` may be the whole first token (`env python3`) or the last
            // path segment (`/usr/bin/env python3`). In both cases the
            // interpreter is the next token.
            let first_base = first.split('/').next_back().unwrap_or(first);
            let base = if first_base == "env" {
                tokens.next().unwrap_or("")
            } else {
                first_base
            };
            if base.starts_with("python") {
                return Some(Language::Python);
            }
            if base == "bash" || base == "sh" || base == "dash" || base == "zsh" || base == "ash" {
                return Some(Language::Shell);
            }
            if base == "node" || base == "bun" || base == "deno" {
                return Some(Language::JavaScript);
            }
        }
    }
    None
}

/// Language of a file plus why it is flagged, for diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Flag {
    pub path: String,
    pub language: Language,
    pub reason: String,
}

/// A gate over a set of files (relative paths + first lines).
pub struct Gate {
    /// Browser-export JavaScript allowlist (exact relative paths). These are
    /// provenance-marked, standalone-page-only and can never become an
    /// extension/package/generator/test/host dependency.
    pub js_allowlist: BTreeSet<String>,
    /// Grandfathered legacy foreign-language files (exact relative paths).
    /// Generated by `--write-manifest` and reviewed; new files not in this
    /// set are rejected.
    pub legacy: BTreeSet<String>,
}

impl Gate {
    pub fn new(js_allowlist: BTreeSet<String>, legacy: BTreeSet<String>) -> Self {
        Gate { js_allowlist, legacy }
    }

    /// Returns the set of files that violate the gate. Empty means pass.
    pub fn violations<'a, I>(&self, files: I) -> Vec<Flag>
    where
        I: IntoIterator<Item = (&'a str, Option<&'a str>)>,
    {
        let mut flags = Vec::new();
        for (rel, first_line) in files {
            let path = Path::new(rel);
            let Some(language) = detect(path, first_line) else {
                continue;
            };
            match language {
                Language::JavaScript => {
                    if self.js_allowlist.contains(rel) {
                        continue;
                    }
                    flags.push(Flag {
                        path: rel.to_owned(),
                        reason: ".js outside the browser-export allowlist".to_owned(),
                        language,
                    });
                }
                _ => {
                    if self.legacy.contains(rel) {
                        continue;
                    }
                    let reason = match language {
                        Language::TypeScript => "new first-party TypeScript".to_owned(),
                        Language::Python => "new first-party Python".to_owned(),
                        Language::Shell => "new first-party shell".to_owned(),
                        _ => "new first-party foreign-language file".to_owned(),
                    };
                    flags.push(Flag {
                        path: rel.to_owned(),
                        reason: reason.to_owned(),
                        language,
                    });
                }
            }
        }
        flags.sort_by(|a, b| a.path.cmp(&b.path));
        flags
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    fn gate() -> Gate {
        Gate::new(BTreeSet::new(), BTreeSet::new())
    }

    #[test]
    fn detects_extensions() {
        assert_eq!(
            detect(Path::new("a.ts"), Some("// x")),
            Some(Language::TypeScript)
        );
        assert_eq!(
            detect(Path::new("a.py"), Some("# x")),
            Some(Language::Python)
        );
        assert_eq!(
            detect(Path::new("a.sh"), Some("#! /bin/sh")),
            Some(Language::Shell)
        );
        assert_eq!(
            detect(Path::new("a.js"), Some("// x")),
            Some(Language::JavaScript)
        );
    }

    #[test]
    fn detects_shebangs() {
        assert_eq!(
            detect(Path::new("tool"), Some("#!/usr/bin/env python3")),
            Some(Language::Python)
        );
        assert_eq!(
            detect(Path::new("tool"), Some("#!/usr/bin/env bash")),
            Some(Language::Shell)
        );
        assert_eq!(
            detect(Path::new("tool"), Some("#!/bin/sh")),
            Some(Language::Shell)
        );
        assert_eq!(
            detect(Path::new("tool"), Some("#!/usr/bin/env bun")),
            Some(Language::JavaScript)
        );
        assert_eq!(
            detect(Path::new("tool"), Some("#!/usr/bin/env node")),
            Some(Language::JavaScript)
        );
    }

    #[test]
    fn ignores_rust_lua_json() {
        assert_eq!(detect(Path::new("x.rs"), Some("//")), None);
        assert_eq!(detect(Path::new("x.lua"), Some("--")), None);
        assert_eq!(detect(Path::new("x.json"), Some("{")), None);
        assert_eq!(detect(Path::new("x.md"), Some("#")), None);
    }

    #[test]
    fn rejects_new_foreign_files() {
        let g = gate();
        let flags = g.violations([("a.ts", Some("//")), ("b.lua", Some("--"))]);
        assert_eq!(flags.len(), 1);
        assert_eq!(flags[0].path, "a.ts");
    }

    #[test]
    fn rejects_js_outside_allowlist_but_allows_listed() {
        let mut allow = BTreeSet::new();
        allow.insert("vendor/lib.js".to_owned());
        let g = Gate::new(allow, BTreeSet::new());
        let flags = g.violations([
            ("vendor/lib.js", Some("//")),
            ("other.js", Some("//")),
        ]);
        assert_eq!(flags.len(), 1);
        assert_eq!(flags[0].path, "other.js");
    }

    #[test]
    fn allows_grandfathered_legacy() {
        let mut legacy = BTreeSet::new();
        legacy.insert("scripts/update-model-catalog.ts".to_owned());
        let g = Gate::new(BTreeSet::new(), legacy);
        let flags = g.violations([("scripts/update-model-catalog.ts", Some("#!/usr/bin/env bun"))]);
        assert!(flags.is_empty());
    }
}