//! pi-rs-tools — A.3 source-language gate.
//!
//! Repository-owned generators/inventory tools must ship as Rust/Lua so that
//! `nix flake check` needs no repository-owned foreign-language runtime. This
//! crate hosts the gate that enforces that: it rejects new first-party `.ts`,
//! `.py`, `.sh`, Python/shell shebangs, and `.js` outside the total allowlist
//! (`tests/source-language/allowlist.json`) while grandfathering the current
//! checked-in footprint in `tests/source-language/legacy.json`.
//!
//! The two JSON manifests are generated by this tool (`--write-manifests`)
//! and reviewed as part of the migration. The gate fails closed: any tracked
//! file whose extension or shebang marks a foreign language and which is not
//! enumerated in the allowlist/legacy manifests is a rejection.

pub mod acquire;
pub mod construction_inventory;
pub mod construction_inventory_selftest;
pub mod dogfood_oracle;
pub mod dogfood_selftest;
pub mod extension_inventory;
pub mod extension_inventory_selftest;
pub mod external_extension_inventory;
pub mod external_extension_inventory_selftest;
pub mod final_parity_audit;
pub mod gate;
pub mod jsvalue;
pub mod manifest;
pub mod model_catalog;
pub mod selftest;
