//! Compiled-grammar catalog loading for the highlight.js 10.7.3 port.
//!
//! The catalog (`data/hljs-grammars.json`, regenerated by
//! `scripts/hljs-grammars`) holds the mode graph exactly as the vendored
//! library's `compileLanguage` produced it; this module deserializes it,
//! translates the JavaScript regex sources to `fancy-regex`, and rebuilds
//! the `MultiRegex`/`ResumableMultiRegex` machinery (including `join`'s
//! backreference renumbering and the shared mutable rule positions the
//! original mutates when it lazily builds matcher variants).

use std::collections::HashMap;
use std::sync::{Arc, LazyLock, Mutex};

use super::HljsError;

// ---------------------------------------------------------------------------
// JSON schema (tests/hljs-parity/gen-grammars.ts output)
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct CatalogJson {
    languages: Vec<LanguageJson>,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct LanguageJson {
    name: String,
    case_insensitive: bool,
    aliases: Vec<String>,
    class_name_aliases: HashMap<String, String>,
    superset_of: Option<String>,
    disable_autodetect: bool,
    root: usize,
    modes: Vec<ModeJson>,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct ModeJson {
    class_name: Option<String>,
    keywords: Option<HashMap<String, (String, f64)>>,
    keyword_pattern: Option<String>,
    end_re: Option<String>,
    skip: bool,
    exclude_begin: bool,
    exclude_end: bool,
    return_begin: bool,
    return_end: bool,
    ends_with_parent: bool,
    ends_parent: bool,
    end_same_as_begin: bool,
    sub_language: Option<serde_json::Value>,
    relevance: f64,
    before_begin: Option<String>,
    on_begin: Option<String>,
    on_end: Option<String>,
    starts: Option<usize>,
    rules: Vec<RuleJson>,
}

#[derive(serde::Deserialize)]
struct RuleJson {
    #[serde(rename = "type")]
    kind: String,
    re: Option<String>,
    groups: usize,
    mode: Option<usize>,
}

// ---------------------------------------------------------------------------
// Loaded structures
// ---------------------------------------------------------------------------

/// Named runtime callbacks — the only grammar functions that survive
/// compilation in the scoped set (gen-grammars.ts errors on anything else).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum Callback {
    /// core.js SHEBANG `on:begin`: ignore unless the match is at index 0.
    Shebang,
    /// core.js END_SAME_AS_BEGIN `on:begin`: stash `m[1]`.
    EndSameAsBeginBegin,
    /// core.js END_SAME_AS_BEGIN `on:end`: ignore unless `m[1]` equals the stash.
    EndSameAsBeginEnd,
    /// javascript.js `isTrulyOpeningTag` (JSX `<tag` disambiguation).
    IsTrulyOpeningTag,
}

fn callback(name: &str) -> Result<Callback, HljsError> {
    match name {
        "shebang" => Ok(Callback::Shebang),
        "end-same-as-begin:begin" => Ok(Callback::EndSameAsBeginBegin),
        "end-same-as-begin:end" => Ok(Callback::EndSameAsBeginEnd),
        "is-truly-opening-tag" => Ok(Callback::IsTrulyOpeningTag),
        other => Err(HljsError::Catalog(format!("unknown callback '{other}'"))),
    }
}

#[derive(Clone, Debug)]
pub(crate) enum SubLanguage {
    None,
    Name(String),
    /// Empty list = auto-detect over every registered language.
    Auto(Vec<String>),
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum RuleKind {
    Begin,
    End,
    Illegal,
}

pub(crate) struct Rule {
    pub kind: RuleKind,
    pub source: String,
    pub groups: usize,
    pub mode: Option<usize>,
}

pub(crate) struct Mode {
    pub class_name: Option<String>,
    pub keywords: Option<HashMap<String, (String, f64)>>,
    pub keyword_pattern: Option<JsRegex>,
    pub end_re: Option<Arc<JsRegex>>,
    pub skip: bool,
    pub exclude_begin: bool,
    pub exclude_end: bool,
    pub return_begin: bool,
    pub return_end: bool,
    pub ends_with_parent: bool,
    pub ends_parent: bool,
    pub end_same_as_begin: bool,
    pub sub_language: SubLanguage,
    pub relevance: f64,
    pub before_begin_dot: bool,
    pub on_begin: Option<Callback>,
    pub on_end: Option<Callback>,
    pub starts: Option<usize>,
    pub rules: Vec<Rule>,
    /// Count of `begin` rules — the ResumableMultiRegex wrap-around point.
    pub begin_count: usize,
    /// The owning language's case sensitivity (matcher variants share it).
    pub case_insensitive: bool,
    /// Lazily built matcher variants plus the *shared* per-rule `position`
    /// values the original mutates on every variant build (rule opts objects
    /// are reused across MultiRegexes, so the latest build wins — ported
    /// bug-for-bug).
    matchers: Mutex<MatcherCache>,
}

struct MatcherCache {
    built: HashMap<usize, Arc<Matcher>>,
    positions: Vec<usize>,
}

pub(crate) struct Language {
    pub name: String,
    pub case_insensitive: bool,
    pub class_name_aliases: HashMap<String, String>,
    pub superset_of: Option<String>,
    pub disable_autodetect: bool,
    pub root: usize,
    pub modes: Vec<Mode>,
}

pub(crate) struct Registry {
    pub languages: Vec<Language>,
    by_name: HashMap<String, usize>,
}

static CATALOG_JSON: &str = include_str!("../../data/hljs-grammars.json");
static REGISTRY: LazyLock<Result<Registry, HljsError>> = LazyLock::new(load);

impl Registry {
    /// The embedded catalog, loaded once.
    pub(crate) fn global() -> Result<&'static Registry, HljsError> {
        match &*REGISTRY {
            Ok(registry) => Ok(registry),
            Err(error) => Err(error.clone()),
        }
    }

    /// core.js `getLanguage`: name or alias, lowercased.
    pub(crate) fn language(&self, name: &str) -> Option<(usize, &Language)> {
        let index = *self.by_name.get(&name.to_lowercase())?;
        Some((index, &self.languages[index]))
    }

    /// `languages[name]` — the exact registry key, aliases not consulted
    /// (the sub-language guard in `processSubLanguage`).
    pub(crate) fn canonical(&self, name: &str) -> Option<usize> {
        self.languages.iter().position(|lang| lang.name == name)
    }
}

fn load() -> Result<Registry, HljsError> {
    let catalog: CatalogJson =
        serde_json::from_str(CATALOG_JSON).map_err(|e| HljsError::Catalog(e.to_string()))?;
    let mut languages = Vec::with_capacity(catalog.languages.len());
    let mut by_name = HashMap::new();
    for lang in catalog.languages {
        let index = languages.len();
        by_name.insert(lang.name.to_lowercase(), index);
        for alias in &lang.aliases {
            by_name.insert(alias.to_lowercase(), index);
        }
        let ci = lang.case_insensitive;
        let mut modes = Vec::with_capacity(lang.modes.len());
        for mode in lang.modes {
            modes.push(load_mode(mode, ci)?);
        }
        languages.push(Language {
            name: lang.name,
            case_insensitive: ci,
            class_name_aliases: lang.class_name_aliases,
            superset_of: lang.superset_of,
            disable_autodetect: lang.disable_autodetect,
            root: lang.root,
            modes,
        });
    }
    Ok(Registry { languages, by_name })
}

fn load_mode(mode: ModeJson, case_insensitive: bool) -> Result<Mode, HljsError> {
    let sub_language = match mode.sub_language {
        None | Some(serde_json::Value::Null) => SubLanguage::None,
        Some(serde_json::Value::String(name)) => SubLanguage::Name(name),
        Some(serde_json::Value::Array(list)) => SubLanguage::Auto(
            list.into_iter()
                .filter_map(|v| v.as_str().map(str::to_owned))
                .collect(),
        ),
        Some(other) => {
            return Err(HljsError::Catalog(format!("bad subLanguage: {other}")));
        }
    };
    let mut rules = Vec::with_capacity(mode.rules.len());
    let mut begin_count = 0;
    for rule in mode.rules {
        let kind = match rule.kind.as_str() {
            "begin" => RuleKind::Begin,
            "end" => RuleKind::End,
            "illegal" => RuleKind::Illegal,
            other => return Err(HljsError::Catalog(format!("bad rule type '{other}'"))),
        };
        if kind == RuleKind::Begin {
            begin_count += 1;
        }
        rules.push(Rule {
            kind,
            source: rule
                .re
                .ok_or_else(|| HljsError::Catalog("rule without regex".into()))?,
            groups: rule.groups,
            mode: rule.mode,
        });
    }
    let positions = (0..rules.len()).collect();
    Ok(Mode {
        class_name: mode.class_name.filter(|name| !name.is_empty()),
        keywords: mode.keywords,
        keyword_pattern: mode
            .keyword_pattern
            .map(|src| JsRegex::new(&src, case_insensitive, true))
            .transpose()?,
        end_re: mode
            .end_re
            .map(|src| JsRegex::new(&src, case_insensitive, false).map(Arc::new))
            .transpose()?,
        skip: mode.skip,
        exclude_begin: mode.exclude_begin,
        exclude_end: mode.exclude_end,
        return_begin: mode.return_begin,
        return_end: mode.return_end,
        ends_with_parent: mode.ends_with_parent,
        ends_parent: mode.ends_parent,
        end_same_as_begin: mode.end_same_as_begin,
        sub_language,
        relevance: mode.relevance,
        before_begin_dot: mode.before_begin.is_some(),
        on_begin: mode.on_begin.as_deref().map(callback).transpose()?,
        on_end: mode.on_end.as_deref().map(callback).transpose()?,
        starts: mode.starts,
        rules,
        begin_count,
        case_insensitive,
        matchers: Mutex::new(MatcherCache {
            built: HashMap::new(),
            positions,
        }),
    })
}

// ---------------------------------------------------------------------------
// Matchers (core.js MultiRegex / lazy ResumableMultiRegex variants)
// ---------------------------------------------------------------------------

pub(crate) struct Matcher {
    regex: JsRegex,
    /// `matchIndexes`: wrapping-group index → absolute rule index.
    map: Vec<(usize, usize)>,
}

pub(crate) struct MatcherHit {
    /// Absolute rule index within the mode.
    pub rule: usize,
    /// `opts.position` at exec time (shared, mutated on variant builds).
    pub position: usize,
    /// Byte index of the match.
    pub index: usize,
    /// Spliced groups: `[0]` is the whole rule match, then the rule's groups.
    pub groups: Vec<Option<String>>,
}

impl Mode {
    /// `ResumableMultiRegex.getMatcher`, including the shared-position
    /// mutation on first build of each variant.
    pub(crate) fn matcher(&self, start: usize) -> Result<Arc<Matcher>, HljsError> {
        let start = start.min(self.rules.len());
        let mut cache = self
            .matchers
            .lock()
            .map_err(|_| HljsError::Catalog("matcher cache poisoned".into()))?;
        if let Some(found) = cache.built.get(&start) {
            return Ok(Arc::clone(found));
        }
        // MultiRegex: addRule for each remaining rule, then compile.
        let mut map = Vec::new();
        let mut match_at = 1;
        let mut sources = Vec::new();
        for (offset, rule) in self.rules[start..].iter().enumerate() {
            cache.positions[start + offset] = offset;
            map.push((match_at, start + offset));
            match_at += rule.groups + 1;
            sources.push(rule.source.as_str());
        }
        let joined = join(&sources, "|");
        let regex = JsRegex::new(&joined, self.case_insensitive, true)?;
        let matcher = Arc::new(Matcher { regex, map });
        cache.built.insert(start, Arc::clone(&matcher));
        Ok(matcher)
    }

    /// Current shared `position` value for a rule.
    pub(crate) fn rule_position(&self, rule: usize) -> usize {
        self.matchers
            .lock()
            .ok()
            .map(|cache| cache.positions[rule])
            .unwrap_or(rule)
    }
}

impl Matcher {
    /// MultiRegex.exec at `lastIndex`.
    pub(crate) fn exec(
        &self,
        mode: &Mode,
        s: &str,
        last_index: usize,
    ) -> Result<Option<MatcherHit>, HljsError> {
        if self.map.is_empty() {
            return Ok(None);
        }
        let Some(caps) = self.regex.captures_at(s, last_index)? else {
            return Ok(None);
        };
        // First non-undefined group > 0 is the matched rule's wrapping group.
        let mut wrapping = None;
        for i in 1..caps.len() {
            if caps.get(i).is_some() {
                wrapping = Some(i);
                break;
            }
        }
        let Some(i) = wrapping else { return Ok(None) };
        let rule = self
            .map
            .iter()
            .rev()
            .find(|(at, _)| *at <= i)
            .map(|(_, rule)| *rule)
            .unwrap_or(0);
        let whole = match caps.get(i) {
            Some(m) => m,
            None => return Ok(None),
        };
        let groups = (i..caps.len())
            .map(|g| caps.get(g).map(|m| m.as_str().to_owned()))
            .collect();
        Ok(Some(MatcherHit {
            rule,
            position: mode.rule_position(rule),
            index: whole.start(),
            groups,
        }))
    }
}

// ---------------------------------------------------------------------------
// join (core.js) — backreference renumbering, ported bug-for-bug
// ---------------------------------------------------------------------------

static BACKREF_RE: LazyLock<Option<fancy_regex::Regex>> = LazyLock::new(|| {
    fancy_regex::Regex::new(r"\[(?:[^\\\]]|\\.)*\]|\(\??|\\([1-9][0-9]*)|\\.").ok()
});

pub(crate) fn join(regexps: &[&str], separator: &str) -> String {
    let Some(backref_re) = BACKREF_RE.as_ref() else {
        // Unreachable: the pattern above is static and valid.
        return regexps
            .iter()
            .map(|re| format!("({re})"))
            .collect::<Vec<_>>()
            .join(separator);
    };
    let mut num_captures = 0usize;
    regexps
        .iter()
        .map(|regex| {
            num_captures += 1;
            let offset = num_captures;
            let mut re: &str = regex;
            let mut out = String::new();
            while !re.is_empty() {
                let Ok(Some(caps)) = backref_re.captures(re) else {
                    out.push_str(re);
                    break;
                };
                let Some(whole) = caps.get(0) else {
                    out.push_str(re);
                    break;
                };
                out.push_str(&re[..whole.start()]);
                let matched = whole.as_str();
                re = &re[whole.end()..];
                if let Some(number) = caps.get(1) {
                    // Adjust the backreference.
                    let value: usize = number.as_str().parse().unwrap_or(0);
                    out.push('\\');
                    out.push_str(&(value + offset).to_string());
                } else {
                    out.push_str(matched);
                    if matched == "(" {
                        num_captures += 1;
                    }
                }
            }
            format!("({out})")
        })
        .collect::<Vec<_>>()
        .join(separator)
}

// ---------------------------------------------------------------------------
// JavaScript regex sources on fancy-regex
// ---------------------------------------------------------------------------

/// A JS `RegExp` stand-in: translated source compiled with `(?m)` (the
/// library compiles every mode regex with the `m` flag) and the language's
/// case sensitivity. "Global" behavior is expressed by searching from a
/// caller-held `lastIndex`.
pub(crate) struct JsRegex {
    regex: fancy_regex::Regex,
}

impl JsRegex {
    pub(crate) fn new(
        source: &str,
        case_insensitive: bool,
        _global: bool,
    ) -> Result<JsRegex, HljsError> {
        let translated = translate(source)?;
        let flags = if case_insensitive { "(?mi)" } else { "(?m)" };
        let regex = fancy_regex::Regex::new(&format!("{flags}{translated}"))
            .map_err(|e| HljsError::Regex(format!("{source:?}: {e}")))?;
        Ok(JsRegex { regex })
    }

    /// A JS `RegExp` without the `m` flag (the session selector's
    /// `new RegExp(pattern, "i")`): `^`/`$` anchor the whole input.
    pub(crate) fn without_multiline(
        source: &str,
        case_insensitive: bool,
    ) -> Result<JsRegex, HljsError> {
        let translated = translate(source)?;
        let flags = if case_insensitive { "(?i)" } else { "" };
        let regex = fancy_regex::Regex::new(&format!("{flags}{translated}"))
            .map_err(|e| HljsError::Regex(format!("{source:?}: {e}")))?;
        Ok(JsRegex { regex })
    }

    /// `RegExp.escape`-style literal (core.js `escape`, used by
    /// `endSameAsBegin`) — compiled with only the `m` flag, like the original.
    pub(crate) fn literal(lexeme: &str) -> Result<JsRegex, HljsError> {
        let mut escaped = String::with_capacity(lexeme.len() * 2);
        for ch in lexeme.chars() {
            if "-/\\^$*+?.()|[]{}".contains(ch) {
                escaped.push('\\');
            }
            escaped.push(ch);
        }
        let regex = fancy_regex::Regex::new(&format!("(?m){escaped}"))
            .map_err(|e| HljsError::Regex(format!("literal {lexeme:?}: {e}")))?;
        Ok(JsRegex { regex })
    }

    /// First match searching from the start (JS non-global `exec`).
    pub(crate) fn find(&self, s: &str) -> Result<Option<(usize, usize)>, HljsError> {
        Ok(self
            .regex
            .find(s)
            .map_err(|e| HljsError::Regex(e.to_string()))?
            .map(|m| (m.start(), m.end())))
    }

    pub(crate) fn captures_at<'h>(
        &self,
        s: &'h str,
        pos: usize,
    ) -> Result<Option<fancy_regex::Captures<'h>>, HljsError> {
        self.regex
            .captures_from_pos(s, pos)
            .map_err(|e| HljsError::Regex(e.to_string()))
    }
}

/// JS `\s` (WhiteSpace + LineTerminator) as Rust class members.
const JS_WHITESPACE: &str = "\\t\\n\\x0B\\x0C\\r \\x{00A0}\\x{1680}\\x{2000}-\\x{200A}\\x{2028}\\x{2029}\\x{202F}\\x{205F}\\x{3000}\\x{FEFF}";

/// Translate a JavaScript regex source to fancy-regex syntax. JS shorthand
/// classes are ASCII (`\d`, `\w`) or the exact ECMAScript whitespace set
/// (`\s`); `[^]`/`\uXXXX` are JS-only spellings; `[`/`&`/`~` are literals
/// inside JS classes but set-operation syntax in Rust.
fn translate(source: &str) -> Result<String, HljsError> {
    let chars: Vec<char> = source.chars().collect();
    let mut out = String::with_capacity(source.len() + 16);
    let mut in_class = false;
    let mut i = 0;
    while i < chars.len() {
        let ch = chars[i];
        if ch == '\\' {
            let Some(&next) = chars.get(i + 1) else {
                out.push('\\');
                i += 1;
                continue;
            };
            match next {
                'd' => out.push_str(if in_class { "0-9" } else { "[0-9]" }),
                'D' if !in_class => out.push_str("[^0-9]"),
                'w' => out.push_str(if in_class {
                    "A-Za-z0-9_"
                } else {
                    "[A-Za-z0-9_]"
                }),
                'W' if !in_class => out.push_str("[^A-Za-z0-9_]"),
                's' => {
                    if in_class {
                        out.push_str(JS_WHITESPACE);
                    } else {
                        out.push('[');
                        out.push_str(JS_WHITESPACE);
                        out.push(']');
                    }
                }
                'S' if !in_class => {
                    out.push_str("[^");
                    out.push_str(JS_WHITESPACE);
                    out.push(']');
                }
                'u' => {
                    // \uXXXX or \u{...} → \x{...}
                    if chars.get(i + 2) == Some(&'{') {
                        out.push_str("\\x");
                        i += 2;
                        continue;
                    }
                    let hex: String = chars.iter().skip(i + 2).take(4).collect();
                    if hex.len() == 4 && hex.chars().all(|c| c.is_ascii_hexdigit()) {
                        out.push_str("\\x{");
                        out.push_str(&hex);
                        out.push('}');
                        i += 6;
                        continue;
                    }
                    out.push_str("\\u");
                }
                '0' if !chars
                    .get(i + 2)
                    .map(|c| c.is_ascii_digit())
                    .unwrap_or(false) =>
                {
                    out.push_str("\\x00");
                }
                '1'..='9' => {
                    // Backreference: keep every following digit attached.
                    out.push('\\');
                    out.push(next);
                    i += 2;
                    while i < chars.len() && chars[i].is_ascii_digit() {
                        out.push(chars[i]);
                        i += 1;
                    }
                    continue;
                }
                _ => {
                    out.push('\\');
                    out.push(next);
                }
            }
            i += 2;
            continue;
        }
        if in_class {
            match ch {
                ']' => {
                    in_class = false;
                    out.push(']');
                }
                '[' => out.push_str("\\["),
                '&' => out.push_str("\\&"),
                '~' => out.push_str("\\~"),
                _ => out.push(ch),
            }
            i += 1;
            continue;
        }
        if ch == '[' {
            if chars.get(i + 1) == Some(&'^') && chars.get(i + 2) == Some(&']') {
                // JS [^] matches anything, including newlines.
                out.push_str("(?s:.)");
                i += 3;
                continue;
            }
            in_class = true;
            out.push('[');
            if chars.get(i + 1) == Some(&'^') {
                out.push('^');
                i += 1;
            }
            // A leading ']' is a literal in JS classes.
            if chars.get(i + 1) == Some(&']') {
                out.push_str("\\]");
                i += 1;
            }
            i += 1;
            continue;
        }
        out.push(ch);
        i += 1;
    }
    Ok(out)
}
