//! Pins the live git-branch discovery for the footer data provider
//! (`core/footer-data-provider.ts`) to Pi's real `FooterDataProvider` via the
//! vendored oracle in `tests/footer-git-parity/oracle.json`, generated by
//! `scripts/footer-git-oracle`. The oracle was produced by driving Pi's own
//! provider over the same `.git` fixtures this test rebuilds on disk; the
//! pi-rs `pi.git.current_branch` mechanism must reproduce each branch name
//! byte-for-byte through the public Lua surface.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::io::Write as _;
use std::path::Path;

use pi_rs_host::{Host, HostConfig};
use serde_json::Value;

const RUNNER: &str = r#"
local pi = ...
pi.register_command("git-branch", {
  handler = function(args)
    local cwd = pi.json.decode(args).cwd
    local branch = pi.git.current_branch(cwd)
    return { branch = branch }
  end,
})
"#;

fn git(args: &[&str], cwd: &Path) {
    let status = std::process::Command::new("git")
        .args(args)
        .current_dir(cwd)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .expect("git runs");
    assert!(status.success(), "git {args:?} failed");
}

fn write(dir: &Path, name: &str, contents: &str) {
    let path = dir.join(name);
    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(contents.as_bytes()).unwrap();
}

/// Rebuild the fixtures used by gen-oracle.ts and resolve each with the
/// mechanism. Returns `(case_name, expected_branch)` from the oracle.
#[test]
fn pi_live_git_branch_matches_vendored_oracle() {
    let oracle = fixture("oracle.json");
    let cases = oracle["cases"].as_array().expect("cases");

    let host = Host::new(HostConfig::default()).expect("host");
    host.load("git-runner", RUNNER).expect("runner loads");

    let root = tempfile::tempdir().unwrap();
    let root_path = root.path();

    // Case 1: normal repo on "main".
    let normal = root_path.join("normal");
    std::fs::create_dir_all(&normal).unwrap();
    git(&["init", "-q", "-b", "main"], &normal);
    write(&normal, "a.txt", "a");
    git(&["add", "a.txt"], &normal);
    git(&["commit", "-q", "-m", "init"], &normal);

    // Case 5: nested cwd inside that same repo.
    let nested = normal.join("sub/dir");
    std::fs::create_dir_all(&nested).unwrap();

    // Case 3: detached HEAD from a second repo.
    let detached = root_path.join("detached");
    std::fs::create_dir_all(&detached).unwrap();
    git(&["init", "-q", "-b", "main"], &detached);
    write(&detached, "a.txt", "a");
    git(&["add", "a.txt"], &detached);
    git(&["commit", "-q", "-m", "init"], &detached);
    git(&["checkout", "-q", "--detach"], &detached);

    // Case 4: plain (non-repo) directory.
    let plain = root_path.join("plain");
    std::fs::create_dir_all(&plain).unwrap();

    // Case 6: worktree — `.git` file linking to the main repo's gitdir.
    let wt_main = root_path.join("wt-main");
    std::fs::create_dir_all(&wt_main).unwrap();
    git(&["init", "-q", "-b", "main"], &wt_main);
    write(&wt_main, "a.txt", "a");
    git(&["add", "a.txt"], &wt_main);
    git(&["commit", "-q", "-m", "init"], &wt_main);
    let wt = root_path.join("wt");
    git(
        &["worktree", "add", "-q", "-b", "wt", wt.to_str().unwrap()],
        &wt_main,
    );

    // Map case names to the fixture cwd we built.
    let fixture_cwd = |name: &str| -> String {
        match name {
            "normal-repo" => normal.to_string_lossy().into_owned(),
            "switch-branch" => normal.to_string_lossy().into_owned(),
            "detached-head" => detached.to_string_lossy().into_owned(),
            "plain-dir" => plain.to_string_lossy().into_owned(),
            "nested-cwd" => nested.to_string_lossy().into_owned(),
            "worktree" => wt.to_string_lossy().into_owned(),
            other => panic!("no fixture for {other}"),
        }
    };

    for case in cases {
        let name = case["name"].as_str().unwrap();
        // Skip `switch-branch`, which tests the async watcher refresh
        // (before/refreshed keys) rather than a synchronous snapshot.
        if name == "switch-branch" {
            continue;
        }
        let want_null = case.get("branch").is_some_and(Value::is_null);
        let want = case["branch"].as_str().map(str::to_owned);
        let cwd = fixture_cwd(name);
        let result = host
            .call_command("git-branch", &serde_json::json!({ "cwd": cwd }).to_string())
            .expect("command")
            .expect("result");
        let got: Option<String> = result["branch"].as_str().map(str::to_owned);

        if want_null {
            assert!(
                got.is_none(),
                "case {name} should have no branch, got {got:?}"
            );
        } else {
            assert_eq!(
                got.as_deref(),
                want.as_deref(),
                "case {name} branch mismatch"
            );
        }
    }
}

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/footer-git-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}
