//! Pins `pi.parse_frontmatter` to Pi's real `utils/frontmatter.ts`
//! (`parseFrontmatter`) via the vendored oracle in
//! tests/frontmatter-parity/oracle.json, generated by
//! scripts/frontmatter-oracle. The oracle is replayed through the public Lua
//! surface, never the Rust module directly.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pi_rs_host::{Host, HostConfig};
use serde_json::Value;

const RUNNER: &str = r#"
local pi = ...
pi.register_command("frontmatter-run", {
  handler = function(args)
    local content = pi.json.decode(args).content
    local ok, result = pcall(function()
      local doc = pi.parse_frontmatter(content)
      return { frontmatter = doc.frontmatter, body = doc.body }
    end)
    if not ok then
      return { threw = true, error = tostring(result) }
    end
    return result
  end,
})
"#;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/frontmatter-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}

#[test]
fn pi_frontmatter_matches_vendored_oracle() {
    let cases = fixture("cases.json");
    let oracle = fixture("oracle.json");

    let host = Host::new(HostConfig::default()).expect("host");
    host.load("frontmatter-runner", RUNNER).expect("runner loads");

    let oracle_cases = oracle["cases"].as_array().expect("oracle cases");
    let mut diffs = Vec::new();
    for (i, oracle_case) in oracle_cases.iter().enumerate() {
        let name = oracle_case["name"].as_str().unwrap_or_default();
        let input = cases["cases"][i]["content"].clone();
        let result = host
            .call_command(
                "frontmatter-run",
                &serde_json::json!({ "content": input }).to_string(),
            )
            .expect("command")
            .expect("result");
        let got = &result;

        // Compare frontmatter and body, accounting for the oracle encoding a
        // throw as `{threw:true, error}`.
        let oracle_frontmatter = oracle_case.get("frontmatter");
        let oracle_body = oracle_case.get("body");
        if oracle_case.get("threw").is_some() {
            if got.get("threw").is_none() {
                diffs.push(format!("{name}: oracle threw but pi-rs returned {got}"));
            }
            continue;
        }
        let got_frontmatter = got.get("frontmatter").cloned().unwrap_or(Value::Null);
        let got_body = got.get("body").cloned().unwrap_or(Value::Null);
        let want_frontmatter = oracle_frontmatter.cloned().unwrap_or(Value::Null);
        let want_body = oracle_body.cloned().unwrap_or(Value::Null);
        if got_frontmatter != want_frontmatter || got_body != want_body {
            diffs.push(format!(
                "{name}:\n  oracle={oracle_case}\n  got   ={got}"
            ));
        }
    }

    if !diffs.is_empty() {
        panic!("frontmatter divergences from Pi oracle ({}):\n{}", diffs.len(), diffs.join("\n"));
    }
}
