//! Pins pi-rs's `parse_git_url` + `is_local_path` source grammar to Pi's real
//! `utils/git.ts` (parseGitUrl) and `utils/paths.ts` (isLocalPath) via the
//! Pi-generated oracle in tests/package-transport-parity/oracle.json
//! (generated by scripts/package-transport-oracle).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pi_rs_host::git::{self, GitSource};
use serde_json::Value;

fn fixture_cases() -> Value {
    let path = format!(
        "{}/../../tests/package-transport-parity/cases.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("cases parse")
}

fn fixture_oracle() -> Value {
    let path = format!(
        "{}/../../tests/package-transport-parity/oracle.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("oracle parse")
}

fn git_to_json(g: &GitSource) -> Value {
    let mut m = serde_json::Map::new();
    m.insert("type".to_owned(), Value::String("git".to_owned()));
    m.insert("repo".to_owned(), Value::String(g.repo.clone()));
    m.insert("host".to_owned(), Value::String(g.host.clone()));
    m.insert("path".to_owned(), Value::String(g.path.clone()));
    if let Some(r) = &g.r#ref {
        m.insert("ref".to_owned(), Value::String(r.clone()));
    }
    m.insert("pinned".to_owned(), Value::Bool(g.pinned));
    Value::Object(m)
}

#[test]
fn git_url_parse_matches_pi_oracle() {
    let cases = fixture_cases();
    let oracle = fixture_oracle();
    let rows = oracle["gitSources"].as_array().unwrap();
    let case_rows = cases["gitSources"].as_array().unwrap();
    assert_eq!(rows.len(), case_rows.len());
    let mut diffs = Vec::new();

    for (row, case_row) in rows.iter().zip(case_rows.iter()) {
        let name = row["name"].as_str().unwrap();
        let source = case_row["source"].as_str().unwrap();
        let want_local = row["isLocalPath"].as_bool().unwrap();
        let got_local = git::is_local_path(source);
        if got_local != want_local {
            diffs.push(format!("{name}/local: got={got_local} want={want_local}"));
        }
        let parsed = git::parse_git_url(source);
        let want = row.get("git").cloned().unwrap_or(Value::Null);
        let got = parsed.as_ref().map(git_to_json).unwrap_or(Value::Null);
        if !(want == got) {
            diffs.push(format!("{name}:\n  oracle={want}\n  got   ={got}"));
        }
    }

    if !diffs.is_empty() {
        panic!(
            "git-parse divergences from Pi oracle ({}):\n{}",
            diffs.len(),
            diffs.join("\n")
        );
    }
}
