//! Pins the native modifier polling mechanism (`tui/native-modifiers.ts`) to
//! Pi's real `native-modifiers.ts` + `terminal.ts` via the vendored oracle in
//! `tests/platform-modifiers-parity/oracle.json`, generated by
//! `scripts/platform-modifiers-oracle`. The oracle is replayed through the
//! public Lua `pi.tui` surface, never the Rust module directly.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pi_rs_host::{Host, HostConfig};
use serde_json::Value;

const RUNNER: &str = r#"
local pi = ...
pi.register_command("modifier-run", {
  handler = function(_args)
    -- modifierProbe: is_native_modifier_pressed over the key vocabulary with
    -- the native helper unavailable (as on this base), matching Pi's oracle.
    local modifiers = {}
    for _, key in ipairs(pi.tui.modifier_keys()) do
      modifiers[#modifiers + 1] = {
        key = key,
        pressed = pi.tui.is_native_modifier_pressed(key),
      }
    end
    -- platform gating: supports_native_modifiers.
    local gating = {}
    for _, probe in ipairs({
      { "darwin", "x64" }, { "darwin", "arm64" }, { "darwin", "ia32" },
      { "linux", "x64" }, { "win32", "x64" }, { "darwin", "" },
    }) do
      gating[#gating + 1] = {
        platform = probe[1], arch = probe[2],
        supported = pi.tui.supports_native_modifiers(probe[1], probe[2]),
      }
    end
    -- normalizeAppleTerminalInput matrix.
    local apple = {}
    for _, data in ipairs({ "\r", "\n", "a", "\t", "\27[13;2u", "\27[Z", " " }) do
      for _, isApple in ipairs({ true, false }) do
        for _, isShift in ipairs({ true, false }) do
          apple[#apple + 1] = {
            data = data, isAppleTerminal = isApple, isShift = isShift,
            out = pi.tui.normalize_apple_terminal_input(data, isApple, isShift),
          }
        end
      end
    end
    return { modifiers = modifiers, gating = gating, apple = apple }
  end,
})
"#;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/platform-modifiers-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}

#[test]
fn pi_native_modifiers_match_vendored_oracle() {
    let oracle = fixture("oracle.json");
    let host = Host::new(HostConfig::default()).expect("host");
    host.load("modifier-runner", RUNNER).expect("runner loads");

    let got = host
        .call_command("modifier-run", "")
        .expect("command")
        .expect("result");

    // 1. modifierProbe — is_native_modifier_pressed with helper unavailable.
    let oracle_probe = oracle["modifierProbe"].as_array().expect("modifierProbe");
    let got_modifiers = got["modifiers"].as_array().expect("modifiers");
    assert_eq!(
        got_modifiers.len(),
        oracle_probe.len(),
        "modifier key count differs"
    );
    for (got_row, want_row) in got_modifiers.iter().zip(oracle_probe.iter()) {
        assert_eq!(got_row, want_row, "modifier probe mismatch");
    }

    // 2. supports_native_modifiers gates on darwin + x64/arm64 (Pi source
    //    `process.platform === "darwin"` and arch check). The oracle's
    //    platform/arch records the run environment; the gating matrix is a
    //    deterministic consequence of the source, asserted directly.
    let gating = got["gating"].as_array().expect("gating");
    let expected: Vec<Value> = vec![
        serde_json::json!({"platform":"darwin","arch":"x64","supported":true}),
        serde_json::json!({"platform":"darwin","arch":"arm64","supported":true}),
        serde_json::json!({"platform":"darwin","arch":"ia32","supported":false}),
        serde_json::json!({"platform":"linux","arch":"x64","supported":false}),
        serde_json::json!({"platform":"win32","arch":"x64","supported":false}),
        serde_json::json!({"platform":"darwin","arch":"","supported":false}),
    ];
    assert_eq!(gating, &expected, "platform gating mismatch");

    // 3. Apple-Terminal Shift+Enter normalization — must match Pi's
    //    `normalizeAppleTerminalInput` byte-for-byte.
    let oracle_apple = oracle["appleNormalized"]
        .as_array()
        .expect("appleNormalized");
    let got_apple = got["apple"].as_array().expect("apple");
    assert_eq!(
        got_apple.len(),
        oracle_apple.len(),
        "apple case count differs"
    );
    for (got_row, want_row) in got_apple.iter().zip(oracle_apple.iter()) {
        assert_eq!(got_row, want_row, "apple normalization mismatch");
    }
}
