//! Pins the native clipboard addon mechanism (`utils/clipboard-native.ts`) to
//! Pi's real `clipboard-native.ts` via the vendored oracle in
//! `tests/platform-clipboard-parity/oracle.json`, generated by
//! `scripts/platform-clipboard-oracle`. The oracle is replayed through the
//! public Lua `pi.clipboard` surface — never the Rust module directly.
//!
//! Covered columns of the oracle:
//!   - `loadProbe` / `noRootOut`: `loadClipboardNative` resolution — walk
//!     require roots in order; the first that resolves
//!     `@mariozechner/clipboard` with `{setText, hasImage, getImageBinary}`
//!     wins; a throwing root advances to the next; empty roots -> null.
//!   - `envProbe`: the module-level gate `!TERMUX_VERSION && hasDisplay`,
//!     `hasDisplay = platform !== "linux" || DISPLAY || WAYLAND_DISPLAY`, which
//!     decides whether the module even attempts a native load.
//!
//! The binary addon is not embedded; its resolution core and gating decision
//! are what the oracle pins.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pi_rs_host::{Host, HostConfig};
use serde_json::Value;

const RUNNER: &str = r#"
local pi = ...

-- A fake `@mariozechner/clipboard` module with Pi's three methods.
local function make_module()
  return {
    setText        = function() end,
    hasImage       = function() return false end,
    getImageBinary = function() return {} end,
  }
end
-- kind 0 => root that resolves the module; kind 1 => root that throws
-- (metatable __index raises), mirroring `require` on a bad root.
local function make_root(kind)
  if kind == 0 then
    return { ["@mariozechner/clipboard"] = make_module() }
  end
  return setmetatable({}, { __index = function() error("module not found") end })
end

pi.register_command("clip-native-run", {
  handler = function(args)
    local opts = pi.json.decode(args)

    -- loadProbe: pure resolution over the root kinds.
    local load_probe = {}
    for _, case in ipairs(opts.loadCases or {}) do
      local roots = {}
      for _, kind in ipairs(case.roots) do roots[#roots + 1] = make_root(kind) end
      local out = pi.clipboard.resolve_native(roots)
      table.insert(load_probe, {
        name = case.name,
        resolved = out.resolved,
        shape = out.resolved and { setText = out.shape.setText, hasImage = out.shape.hasImage, getImageBinary = out.shape.getImageBinary } or nil,
      })
    end

    -- noRootOut: empty require list resolves null without throwing.
    local no_root = pi.clipboard.resolve_native({})
    local no_root_out = no_root.resolved and "non-null" or "null"

    -- envProbe: the module-level gate over env states (on linux platform).
    local env_probe = {}
    for _, case in ipairs(opts.envCases or {}) do
      local env = {}
      if case.termux ~= nil then env.TERMUX_VERSION = case.termux end
      if case.display ~= nil then env.DISPLAY = case.display end
      if case.wayland ~= nil then env.WAYLAND_DISPLAY = case.wayland end
      table.insert(env_probe, {
        name = case.name,
        clipboardLoaded = pi.clipboard.has_display("linux", env),
      })
    end

    return {
      loadProbe = load_probe,
      noRootOut = no_root_out,
      envProbe = env_probe,
    }
  end,
})
"#;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/platform-clipboard-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}

/// Build the require-root kind list for each named loadProbe case. These mirror
/// the `roots` arrays hard-coded in gen-oracle.ts.
fn known_roots(name: &str) -> Vec<Value> {
    let kinds: Vec<i64> = match name {
        "single-resolves" => vec![0],
        "single-absent" => vec![1],
        "first-fails-second-resolves" => vec![1, 0],
        "both-fail" => vec![1, 1],
        "third-resolves" => vec![1, 1, 0],
        _ => panic!("unknown loadProbe case {name}"),
    };
    kinds.into_iter().map(Value::from).collect()
}

/// Build the env-state cases for the gate, matching gen-oracle.ts's envCases.
fn env_cases() -> Vec<Value> {
    vec![
        serde_json::json!({ "name": "linux-no-display", "termux": null, "display": null, "wayland": null }),
        serde_json::json!({ "name": "linux-x11", "termux": null, "display": ":0", "wayland": null }),
        serde_json::json!({ "name": "linux-wayland", "termux": null, "display": null, "wayland": "wayland-1" }),
        serde_json::json!({ "name": "linux-termux", "termux": "0.118", "display": ":0", "wayland": null }),
    ]
}

#[test]
fn pi_native_clipboard_matches_vendored_oracle() {
    let oracle = fixture("oracle.json");
    let host = Host::new(HostConfig::default()).expect("host");
    host.load("clip-native-runner", RUNNER)
        .expect("runner loads");

    // Rebuild the runner inputs from the oracle itself so the case set stays in
    // lockstep with Pi's generation.
    let oracle_load = oracle["loadProbe"].as_array().expect("loadProbe");
    let load_cases: Vec<Value> = oracle_load
        .iter()
        .map(|row| {
            let name = row["name"].as_str().unwrap().to_owned();
            serde_json::json!({ "name": name, "roots": known_roots(&name) })
        })
        .collect();

    let input = serde_json::json!({
        "loadCases": load_cases,
        "envCases": env_cases(),
    });

    let got = host
        .call_command("clip-native-run", &input.to_string())
        .expect("command")
        .expect("result");

    // 1. loadProbe — resolution core.
    let got_load = got["loadProbe"].as_array().expect("got loadProbe");
    assert_eq!(
        got_load.len(),
        oracle_load.len(),
        "loadProbe length differs"
    );
    for (got_row, want_row) in got_load.iter().zip(oracle_load.iter()) {
        assert_eq!(
            got_row["resolved"], want_row["resolved"],
            "loadProbe {} resolution mismatch",
            want_row["name"]
        );
        if want_row["resolved"].as_bool() == Some(true) {
            assert_eq!(
                got_row["shape"], want_row["shape"],
                "loadProbe {} shape mismatch",
                want_row["name"]
            );
        } else {
            assert!(
                got_row["shape"].is_null(),
                "loadProbe {} should have null shape",
                want_row["name"]
            );
        }
    }

    // 2. noRootOut — empty require list resolves null, never throws.
    assert_eq!(
        got["noRootOut"],
        serde_json::json!("null"),
        "noRootOut mismatch"
    );

    // 3. envProbe — module-level gate.
    let oracle_env = oracle["envProbe"].as_array().expect("envProbe");
    let got_env = got["envProbe"].as_array().expect("got envProbe");
    assert_eq!(got_env.len(), oracle_env.len(), "envProbe length differs");
    for (got_row, want_row) in got_env.iter().zip(oracle_env.iter()) {
        assert_eq!(
            got_row["clipboardLoaded"], want_row["clipboardLoaded"],
            "envProbe {} gate mismatch",
            want_row["name"]
        );
    }
}
