//! Pins pi-rs's public prompt-template disk loader (`load_prompt_templates`
//! in the `pi.interactive.prompts` module) to Pi's real
//! `core/prompt-templates.ts` `loadPromptTemplates` via the vendored oracle
//! in tests/prompt-loader-parity/oracle.json, generated by
//! scripts/prompt-loader-oracle.
//!
//! The loader runs through the public Lua surface (`pi.fs`, `pi.path`,
//! `pi.parse_frontmatter`) so the parity covers the authoring mechanism plus
//! the resource-loader provenance (source/scope/origin/baseDir) that Pi's
//! loader attaches.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![allow(clippy::needless_collect)]

use pi_rs_app::builtins::INTERACTIVE_PACK;
use pi_rs_host::{Host, HostConfig};
use serde_json::{Value, json};

const RUNNER: &str = r#"
local pi = ...
pi.register_command("prompt-loader-run", {
  handler = function(args)
    local c = pi.json.decode(args)
    local m = pi.module.require("pi.interactive.prompts", "1")
    local templates = m.load_prompt_templates({
      cwd = c.cwd, agentDir = c.agentDir,
      promptPaths = c.promptPaths, includeDefaults = c.includeDefaults,
    })
    local out = {}
    for _, t in ipairs(templates) do
      local si = t.sourceInfo
      local entry = {
        name = t.name, description = t.description,
        content = t.content, filePath = t.filePath,
        sourceInfo = {
          source = si.source, scope = si.scope, origin = si.origin,
          baseDir = si.baseDir,
        },
      }
      if t.argumentHint ~= nil then entry.argumentHint = t.argumentHint end
      out[#out + 1] = entry
    end
    return { templates = out }
  end,
})
"#;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/prompt-loader-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}

fn arr(v: &Value) -> &Vec<Value> {
    static EMPTY: Vec<Value> = Vec::new();
    v.as_array().unwrap_or(&EMPTY)
}

fn write(path: &std::path::Path, content: &str) {
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, content).unwrap();
}

/// Relativize an absolute path against `root`, stripping `root/`; paths equal
/// to root stay as-is.
fn rel(p: &str, root: &str) -> String {
    let prefix = format!("{root}/");
    p.strip_prefix(&prefix).unwrap_or(p).to_owned()
}

/// Sort templates by relative filePath (Pi's readdir order is not
/// deterministic; the oracle records a sorted list).
fn sort_by_path(mut templates: Vec<Value>) -> Vec<Value> {
    templates.sort_by(|a, b| {
        let ap = a["filePath"].as_str().unwrap_or_default();
        let bp = b["filePath"].as_str().unwrap_or_default();
        ap.cmp(bp)
    });
    templates
}

#[test]
fn prompt_loader_matches_pi_oracle() {
    let cases = fixture("cases.json");
    let oracle = fixture("oracle.json");
    let oracle_cases = oracle["cases"].as_array().expect("oracle cases");
    let mut diffs: Vec<String> = Vec::new();

    for (i, oracle_case) in oracle_cases.iter().enumerate() {
        let name = oracle_case["name"].as_str().unwrap_or_default();
        let case = &cases["cases"][i];

        // Seed corpus under a fresh temp root with the same layout the
        // oracle generator uses.
        let root = tempfile::tempdir().expect("tempdir");
        let root_str = root.path().to_string_lossy().into_owned();
        let cwd = root.path().join("cwd");
        let agent_dir = root.path().join("agent");
        std::fs::create_dir_all(cwd.join(".pi/prompts")).unwrap();
        std::fs::create_dir_all(agent_dir.join("prompts")).unwrap();
        write(
            &cwd.join(".pi/prompts/project-md.md"),
            "---\ndescription: Project template description\n---\nProject body $1",
        );
        write(
            &agent_dir.join("prompts/global-md.md"),
            "---\nargument-hint: <arg>\n---\nGlobal body",
        );

        for rel_file in arr(&case["files"]).iter() {
            let rel_path = rel_file.as_str().unwrap();
            let p = root.path().join(rel_path);
            let contents = case["fileContents"]
                .get(rel_path)
                .map(|v| v.as_str().unwrap())
                .unwrap_or("---\ndescription: staged\n---\nStaged body");
            write(&p, contents);
        }

        let prompt_paths_abs: Vec<String> = arr(&oracle_case["promptPaths"])
            .iter()
            .map(|v| {
                root.path()
                    .join(v.as_str().unwrap())
                    .to_string_lossy()
                    .into_owned()
            })
            .collect();
        let include_defaults = oracle_case["includeDefaults"].as_bool().unwrap_or(true);

        let host = Host::new(HostConfig {
            cwd: Some(root_str.clone()),
            ..HostConfig::default()
        })
        .expect("host");
        let report = host.load_embedded(&[INTERACTIVE_PACK]);
        assert!(report.errors.is_empty(), "load errors: {:?}", report.errors);
        host.load("prompt-loader-runner", RUNNER)
            .expect("runner loads");

        let request = json!({
            "cwd": cwd.to_string_lossy(),
            "agentDir": agent_dir.to_string_lossy(),
            "promptPaths": prompt_paths_abs,
            "includeDefaults": include_defaults,
        });
        let result = host
            .call_command("prompt-loader-run", &request.to_string())
            .expect("command")
            .expect("result");
        let got_templates: Vec<Value> = result["templates"]
            .as_array()
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .map(|mut t| {
                let fp = t["filePath"].as_str().unwrap_or_default();
                t["filePath"] = Value::String(rel(fp, &root_str));
                if let Some(si) = t.get("sourceInfo").and_then(|v| v.as_object()) {
                    let mut si = si.clone();
                    if let Some(bd) = si.get("baseDir").and_then(|v| v.as_str()) {
                        si.insert("baseDir".into(), Value::String(rel(bd, &root_str)));
                    }
                    t["sourceInfo"] = Value::Object(si);
                }
                t
            })
            .collect();
        // Paths are MPI-absolute in the port; the oracle relativizes too.
        let got_templates = sort_by_path(got_templates);

        let want_templates = oracle_case["templates"]
            .as_array()
            .cloned()
            .unwrap_or_default();

        // Force JSON formatting that drops absent sourceInfo keys == undefined.
        if got_templates != want_templates {
            diffs.push(format!(
                "{name}:\n  oracle={}\n  got   ={}",
                serde_json::to_string_pretty(&want_templates).unwrap(),
                serde_json::to_string_pretty(&got_templates).unwrap()
            ));
        }
    }

    if !diffs.is_empty() {
        panic!(
            "prompt-loader divergences from Pi oracle ({}):\n{}",
            diffs.len(),
            diffs.join("\n")
        );
    }
}
