//! Pins pi-rs's public prompt-template module (`pi.interactive.prompts`) to
//! Pi's real `core/prompt-templates.ts` pure functions (parseCommandArgs,
//! substituteArgs, expandPromptTemplate) via the vendored oracle in
//! tests/prompt-parity/oracle.json, generated by scripts/prompt-oracle.
//!
//! The oracle is replayed through the module surface so the parity covers the
//! public authoring mechanism, not a private port.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pi_rs_app::builtins::INTERACTIVE_PACK;
use pi_rs_host::{Host, HostConfig};
use serde_json::{Value, json};

const RUNNER: &str = r#"
local pi = ...
pi.register_command("prompt-run", {
  handler = function(args)
    local phase = pi.json.decode(args).phase
    local m = pi.module.require("pi.interactive.prompts", "1")
    if phase == "parseArgs" then return { args = m.parse_command_args(pi.json.decode(args).input) } end
    if phase == "substitute" then
      local c = pi.json.decode(args)
      return { result = m.substitute_args(c.content, c.args) }
    end
    if phase == "expand" then
      local c = pi.json.decode(args)
      return { result = m.expand_prompt_template(c.text, c.templates) }
    end
    return {}
  end,
})
"#;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/prompt-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}

fn host() -> Host {
    let host = Host::new(HostConfig::default()).expect("host");
    let report = host.load_embedded(&[INTERACTIVE_PACK]);
    assert!(report.errors.is_empty(), "load errors: {:?}", report.errors);
    host.load("prompt-runner", RUNNER).expect("runner loads");
    host
}

fn run_phase(host: &Host, phase: &str, payload: Value) -> Value {
    let mut request = serde_json::Map::new();
    request.insert("phase".to_owned(), Value::String(phase.to_owned()));
    if let Value::Object(map) = payload {
        for (k, v) in map {
            request.insert(k, v);
        }
    }
    host.call_command("prompt-run", &Value::Object(request).to_string())
        .expect("command")
        .expect("result")
}

#[test]
fn prompt_template_functions_match_pi_oracle() {
    let cases = fixture("cases.json");
    let oracle = fixture("oracle.json");
    let host = host();
    let mut diffs: Vec<String> = Vec::new();

    for (i, oc) in oracle["parseArgs"].as_array().unwrap().iter().enumerate() {
        let name = oc["name"].as_str().unwrap();
        let input = cases["parseArgs"][i]["input"].as_str().unwrap();
        let got = run_phase(&host, "parseArgs", serde_json::json!({ "input": input }));
        let want = oc.get("args").cloned().unwrap_or(Value::Null);
        let got_args = got.get("args").cloned().unwrap_or(Value::Null);
        // An empty Lua table crosses the boundary as `{}` while Pi records an
        // empty array `[]`; treat both empty representations as equal.
        let want_empty = want.as_array().is_some_and(|a| a.is_empty());
        let got_empty = got_args.as_array().is_some_and(|a| a.is_empty())
            || got_args.as_object().is_some_and(|o| o.is_empty());
        if !(want == got_args || (want_empty && got_empty)) {
            diffs.push(format!(
                "parseArgs/{name}:\n  oracle={want}\n  got   ={got_args}"
            ));
        }
    }

    for (i, oc) in oracle["substitute"].as_array().unwrap().iter().enumerate() {
        let name = oc["name"].as_str().unwrap();
        let content = cases["substitute"][i]["content"].as_str().unwrap();
        let args = cases["substitute"][i]["args"].clone();
        let got = run_phase(
            &host,
            "substitute",
            serde_json::json!({ "content": content, "args": args }),
        );
        let want = oc.get("result").cloned().unwrap_or(Value::Null);
        let got_res = got.get("result").cloned().unwrap_or(Value::Null);
        if got_res != want {
            diffs.push(format!(
                "substitute/{name}:\n  oracle={want}\n  got   ={got_res}"
            ));
        }
    }

    for (i, oc) in oracle["expand"].as_array().unwrap().iter().enumerate() {
        let name = oc["name"].as_str().unwrap();
        let text = cases["expand"][i]["text"].as_str().unwrap();
        let templates = cases["expand"][i]["templates"].clone();
        let got = run_phase(
            &host,
            "expand",
            serde_json::json!({ "text": text, "templates": templates }),
        );
        let want = oc.get("result").cloned().unwrap_or(Value::Null);
        let got_res = got.get("result").cloned().unwrap_or(Value::Null);
        if got_res != want {
            diffs.push(format!(
                "expand/{name}:\n  oracle={want}\n  got   ={got_res}"
            ));
        }
    }

    if !diffs.is_empty() {
        panic!(
            "prompt-template divergences from Pi oracle ({}):\n{}",
            diffs.len(),
            diffs.join("\n")
        );
    }
}

/// A file-backed package imports the prompt-template module through the same
/// exact-version mechanism the interactive builtin uses — no hidden native
/// module or JS runtime. Proves embedded and file-backed packages share one
/// dependency mechanism for the PLAN 9.7 prompt/resource helpers.
#[test]
fn file_backed_package_imports_prompt_template_module() {
    let host = host();
    host.load(
        "examples/extensions/prompts-consumer.lua",
        include_str!("../../../examples/extensions/prompts-consumer.lua"),
    )
    .expect("file-backed prompts consumer loads");
    let result = host
        .call_command("prompts-consumer", r#"{"args":["add","two","words"]}"#)
        .expect("prompts consumer runs")
        .expect("prompts consumer result");
    assert_eq!(result["tokens"], json!(["add", "two", "words"]));
    assert_eq!(result["substituted"], "add two words");
    assert_eq!(result["expanded"], "Plan: add");
}
