//! Pins pi-rs's public skill loader (`pi.resources.skills` module
//! `load_skills_from_dir`) to Pi's real `core/skills.ts` `loadSkillsFromDir`
//! via the vendored oracle in tests/skills-parity/oracle.json, generated by
//! scripts/skills-oracle.
//!
//! The loader runs through the public Lua surface (`pi.fs`, `pi.path`,
//! `pi.parse_frontmatter`) so the parity covers the authoring mechanism and
//! the provenance Pi attaches to each discovered skill.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![allow(clippy::needless_collect, clippy::redundant_closure)]

use pi_rs_app::builtins::INTERACTIVE_PACK;
use pi_rs_host::{Host, HostConfig};
use serde_json::{Value, json};

const RUNNER: &str = r#"
local pi = ...
pi.register_command("skills-run", {
  handler = function(args)
    local c = pi.json.decode(args)
    local m = pi.module.require("pi.resources.skills", "1")
    local result = m.load_skills_from_dir(c.dir, c.source)
    local out = { skills = {}, diagnostics = {} }
    for _, s in ipairs(result.skills) do
      local si = s.sourceInfo
      out.skills[#out.skills + 1] = {
        name = s.name, description = s.description,
        filePath = s.filePath, baseDir = s.baseDir,
        disableModelInvocation = s.disableModelInvocation,
        sourceInfo = {
          source = si.source, scope = si.scope, origin = si.origin,
          baseDir = si.baseDir,
        },
      }
    end
    for _, d in ipairs(result.diagnostics) do
      local e = { type = d.type, message = d.message }
      if d.path ~= nil then e.path = d.path end
      out.diagnostics[#out.diagnostics + 1] = e
    end
    return out
  end,
})
"#;

fn fixture(name: &str) -> Value {
    let path = format!(
        "{}/../../tests/skills-parity/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&raw).expect("fixture parses")
}

fn arr(v: &Value) -> &Vec<Value> {
    static EMPTY: Vec<Value> = Vec::new();
    v.as_array().unwrap_or(&EMPTY)
}

fn write(path: &std::path::Path, content: &str) {
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, content).unwrap();
}

fn rel(p: &str, root: &str) -> String {
    let prefix = format!("{root}/");
    p.strip_prefix(&prefix).unwrap_or(p).to_owned()
}

fn sort_by_key(mut items: Vec<Value>, key: &str) -> Vec<Value> {
    items.sort_by(|a, b| {
        let ap = a[key].as_str().unwrap_or_default();
        let bp = b[key].as_str().unwrap_or_default();
        ap.cmp(bp)
    });
    items
}

#[test]
fn skills_from_dir_match_pi_oracle() {
    let cases = fixture("cases.json");
    let oracle = fixture("oracle.json");
    let oracle_cases = oracle["cases"].as_array().expect("oracle cases");
    let mut diffs: Vec<String> = Vec::new();

    for (i, oracle_case) in oracle_cases.iter().enumerate() {
        let name = oracle_case["name"].as_str().unwrap_or_default();
        let case = &cases["cases"][i];

        let root = tempfile::tempdir().expect("tempdir");
        let root_str = root.path().to_string_lossy().into_owned();
        let dir_rel = case["dir"].as_str().unwrap_or("skills");
        let dir = root.path().join(dir_rel);
        std::fs::create_dir_all(&dir).unwrap();
        for (rel_file, contents) in case["files"].as_object().unwrap_or(&serde_json::Map::new()) {
            let p = dir.join(rel_file);
            let contents = contents.as_str().unwrap_or("");
            let expanded = contents.replace("$LONG_1100$", &"x".repeat(1100));
            write(&p, &expanded);
        }

        let source = case["source"].as_str().unwrap_or("path").to_owned();

        let host = Host::new(HostConfig {
            cwd: Some(root_str.clone()),
            ..HostConfig::default()
        })
        .expect("host");
        let report = host.load_embedded(&[INTERACTIVE_PACK]);
        assert!(report.errors.is_empty(), "load errors: {:?}", report.errors);
        host.load("skills-runner", RUNNER).expect("runner loads");

        let request = json!({
            "dir": dir.to_string_lossy(),
            "source": source,
        });
        let result = host
            .call_command("skills-run", &request.to_string())
            .expect("command")
            .expect("result");

        let got_skills: Vec<Value> = arr(&result["skills"])
            .iter()
            .cloned()
            .map(|mut s| {
                s["filePath"] = Value::String(rel(s["filePath"].as_str().unwrap_or(""), &root_str));
                s["baseDir"] = Value::String(rel(s["baseDir"].as_str().unwrap_or(""), &root_str));
                if let Some(si) = s.get("sourceInfo").and_then(|v| v.as_object()).cloned() {
                    let mut si = si;
                    if let Some(bd) = si.get("baseDir").and_then(|v| v.as_str()) {
                        si.insert("baseDir".into(), Value::String(rel(bd, &root_str)));
                    }
                    s["sourceInfo"] = Value::Object(si);
                }
                s
            })
            .collect();
        let got_skills = sort_by_key(got_skills, "filePath");

        let got_diags: Vec<Value> = arr(&result["diagnostics"])
            .iter()
            .cloned()
            .map(|mut d| {
                if let Some(p) = d.get("path").and_then(|v| v.as_str()) {
                    d["path"] = Value::String(rel(p, &root_str));
                }
                d
            })
            .collect();
        // Diagnostics order derives from Pi's nondeterministic readdir; sort
        // by path for a stable diff (matches the oracle generator).
        let mut got_diags = got_diags;
        got_diags.sort_by(|a, b| {
            a["path"]
                .as_str()
                .unwrap_or_default()
                .cmp(b["path"].as_str().unwrap_or_default())
        });

        let want_skills = oracle_case["skills"]
            .as_array()
            .cloned()
            .unwrap_or_default();
        let want_diags = oracle_case["diagnostics"]
            .as_array()
            .cloned()
            .unwrap_or_default();

        if got_skills != want_skills || got_diags != want_diags {
            diffs.push(format!(
                "{name}:\n  skills oracle={}\n  skills got  ={}\n  diag oracle={}\n  diag got   ={}",
                serde_json::to_string_pretty(&want_skills).unwrap(),
                serde_json::to_string_pretty(&got_skills).unwrap(),
                serde_json::to_string_pretty(&want_diags).unwrap(),
                serde_json::to_string_pretty(&got_diags).unwrap()
            ));
        }
    }

    if !diffs.is_empty() {
        panic!(
            "skills divergences from Pi oracle ({}):\n{}",
            diffs.len(),
            diffs.join("\n")
        );
    }
}

/// A file-backed package imports the public skill loader through the same
/// exact-version mechanism the embedded interactive pack uses — no hidden
/// native module or JS runtime. Proves embedded and file-backed packages
/// share one dependency mechanism for the PLAN 9.7 skill loader.
#[test]
fn file_backed_package_imports_skill_loader() {
    let root = tempfile::tempdir().expect("tempdir");
    let dir = root.path().join("skills");
    std::fs::create_dir_all(dir.join("review")).unwrap();
    std::fs::write(
        dir.join("review/SKILL.md"),
        "---\nname: review\ndescription: Review code\n---\nCheck correctness.\n",
    )
    .unwrap();
    std::fs::write(
        dir.join("inline.md"),
        "---\ndescription: An inline skill\n---\nInline body.\n",
    )
    .unwrap();

    let host = Host::new(HostConfig {
        cwd: Some(root.path().to_string_lossy().into_owned()),
        ..HostConfig::default()
    })
    .expect("host");
    let report = host.load_embedded(&[INTERACTIVE_PACK]);
    assert!(report.errors.is_empty(), "load errors: {:?}", report.errors);
    host.load(
        "examples/extensions/skills-consumer.lua",
        include_str!("../../../examples/extensions/skills-consumer.lua"),
    )
    .expect("file-backed skills consumer loads");

    let result = host
        .call_command(
            "skills-consumer",
            &json!({ "dir": dir.to_string_lossy(), "source": "path" }).to_string(),
        )
        .expect("skills consumer runs")
        .expect("skills consumer result");
    assert_eq!(result["count"], json!(2));
    assert_eq!(result["diagnostics"], json!(0));
    let prompt = result["prompt"].as_str().unwrap();
    // Both skills render as an available_skills XML block, sorted by path.
    assert!(prompt.contains("<name>review</name>"));
    assert!(prompt.contains("<name>skills</name>"));
    assert!(prompt.contains("</available_skills>"));
}
